### ISSUE TITLE
destroy e show

### ISSUE THREAD

**Issue by Leo9723** [Leo9723/Movies-Laravel#24]
crea, poi uccidi

**Comment by robertvlad** [comment]
Ciao, ho fatto la show e il delete per one-to-many e many-to-many. Ho aggiunto anche i tasti alla index per le view genere e cast in modo da visualizzare, modificare, o eliminare. Infine ho aggiunto il paramete nella route, perchè altrimenti mostarva 404 nella visualizzazione della singola pagina
